### ISSUE TITLE
Shapes that have been split by eraser hold reverences to each other

### ISSUE THREAD

**Issue by casperlamboo** [Doodle3D/Doodle3D-Slicer#17]
Shapes that have been split by eraser hold reverences to each other. This is demonstrated in the attached gif
![out](https://cloud.githubusercontent.com/assets/6638028/13532107/00a2a1fe-e22a-11e5-8e78-9a5a306904c1.gif)

**Comment by peteruithoven** [comment]
I'm also getting the following error: 

```
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values.
```

**Comment by peteruithoven** [comment]
Wrong repo
