### ISSUE TITLE
Fix geometry type check

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/Doodle3D-Slicer#21]
The slicer has the following geometry type check: https://github.com/Doodle3D/Doodle3D-Slicer/blob/develop/src/Slicer.js#L14-L20
When creating for example a TorusGeometry this type is set to `TorusGeometry`, causing that check to fail. A workaround is to clone the TorusGeometry. 
const geometry = new THREE.TorusGeometry(20, 10, 30, 30).clone();

Isn't there a better way to check this? 
Are the [geometry.isGeometry](https://threejs.org/docs/index.html#api/core/Geometry.isGeometry) & [bufferGeometry.isBufferGeometry](https://threejs.org/docs/index.html#api/core/BufferGeometry.isBufferGeometry) functions interesting?

**Comment by casperlamboo** [comment]
This check is also used to distinguish between THREE.BufferGeometry and THREE.Geometry.
