### ISSUE TITLE
Use Settings only internally?

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/Doodle3D-Slicer#22]
Currently we ask users of this package to put settings in the `SLICER.Settings` object first and give `slice()` the resulting instance. 
Why not put the settings into this object inside the slice function? Benefits:
- Less api
- No confusion between the default settings objects and this Settings class

**Comment by casperlamboo** [comment]
I;ve completely removed the settings classed as it is only used to replace some strings in the start and endcode. This start and end code is not needed any more as it is added in the WiFi box
