### ISSUE TITLE
Some areas are printed hollow

### ISSUE THREAD

**Issue by companje** [Doodle3D/Doodle3D-Slicer#26]
![img_5119](https://user-images.githubusercontent.com/156066/28833158-ceafcece-76de-11e7-9b4a-5e3f2509be6a.JPG)

here's the sketch file:
[noodlebot small.d3sketch.zip](https://github.com/Doodle3D/Doodle3D-Slicer/files/1191082/noodlebot.small.d3sketch.zip)

**Comment by jeroensomers** [comment]
Same with this file
Here are the files Casper needed from me.
[keychain.zip](https://github.com/Doodle3D/Doodle3D-Slicer/files/1320941/keychain.zip)

**Comment by casperlamboo** [comment]
This was caused by the generation of the 3d file. Fixed in https://github.com/Doodle3D/Doodle3D-App/commit/5f9c0ce9a0d6f9eb9041925d4ac544997fd173b2
