### ISSUE TITLE
end and start slice code in slice logic 

### ISSUE THREAD

**Issue by jeroensomers** [Doodle3D/Doodle3D-Slicer#27]
The order of the nozzle and bed heat must be changed.
Now the nozzle heats first and after it reaches it's target temp the printer starts heating up the bed.
This way the nozzle can leak some serious pla before getting started to print.

So first heat the bed to its target temp and then heat up the nozzle.

**Comment by casperlamboo** [comment]
Currently the start and end code is handled in by Doodle3D Connect. We would like to move this to the slicer logic.

**Comment by casperlamboo** [comment]
Slicer is now able to add start and end code https://github.com/Doodle3D/Doodle3D-Slicer/commit/10fb3714c78665d81fbd0e2ac005eb2c14868a12.

However, the start and endcodes still have to be added in the settings (https://github.com/Doodle3D/Doodle3D-Slicer/blob/master/src/settings/printer.yml)
