### ISSUE TITLE
Find ClipperJS alternative? 

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/Doodle3D-Slicer#9]
Currently we use [a javascript port](https://github.com/Doodle3D/Doodle3D-Slicer/blob/master/library/clipper.js) of [Clipper](http://www.angusj.com/delphi/clipper.php) (Probably [JSClipper](http://sourceforge.net/projects/jsclipper)). 
Can we find, more up to date, optimized alternatives? 
Examples:
- https://www.npmjs.com/package/greiner-hormann ([example](http://w8r.github.io/GreinerHormann/)
- https://www.npmjs.com/package/polygon-offset ([example](http://w8r.github.io/polygon-offset)) (uses the greiner-hormann package)
- https://www.npmjs.com/package/2d-polygon-boolean
- https://www.npmjs.com/package/curve-intersection
- [Paper.js](http://paperjs.org) seems to have [boolean operations](http://paperjs.org/reference/path/#unite-path)
- https://www.npmjs.com/package/polygon-direction
- [Polygon related packages on NPM](https://www.npmjs.com/browse/keyword/polygon)

**Comment by casperlamboo** [comment]
We should keep in mind that ClipperJS is not only used for vector boolean operations but it is also used for offsetting paths (scaling the lines of a path along its normal).

**Comment by peteruithoven** [comment]
Totally true. Maybe we can use that [polygon-offset](https://www.npmjs.com/package/polygon-offset) package?

**Comment by peteruithoven** [comment]
The clipper fork on npm/github: https://www.npmjs.com/package/clipper-lib (which seems the best Clipper fork on npm)
